export const Questions = [
    {
      prompt: "What does CPU stand for?",
      optionA: "Central Processing Unit",
      optionB: "Central Programming Unit",
      optionC: "Computer Personal Unit",
      optionD: "Centralized Processing Unit",
      answer: "A",
    },
    {
      prompt: "Which data structure uses LIFO (Last In First Out) principle?",
      optionA: "Queue",
      optionB: "Stack",
      optionC: "Linked List",
      optionD: "Tree",
      answer: "B",
    },
    {
      prompt: "What is the time complexity of binary search algorithm?",
      optionA: "O(n)",
      optionB: "O(log n)",
      optionC: "O(n log n)",
      optionD: "O(1)",
      answer: "B",
    },
    {
      prompt: "Which of these is a non-volatile memory?",
      optionA: "RAM",
      optionB: "Cache",
      optionC: "Hard Disk",
      optionD: "Registers",
      answer: "C",
    },
    {
      prompt: "What is the purpose of an operating system?",
      optionA: "To manage hardware resources",
      optionB: "To compile source code",
      optionC: "To perform mathematical calculations",
      optionD: "To manage web servers",
      answer: "A",
    },
    {
      prompt: "Which of the following is a high-level programming language?",
      optionA: "Assembly",
      optionB: "C",
      optionC: "Machine Code",
      optionD: "Binary",
      answer: "B",
    },
    {
      prompt: "What does the acronym HTTP stand for?",
      optionA: "HyperText Transfer Protocol",
      optionB: "Hyper Transfer Text Protocol",
      optionC: "HyperText Transmission Protocol",
      optionD: "Hyper Transfer Transmission Protocol",
      answer: "A",
    },
    {
      prompt: "In which phase of software development is the software tested for bugs?",
      optionA: "Design",
      optionB: "Implementation",
      optionC: "Testing",
      optionD: "Maintenance",
      answer: "C",
    },
    {
      prompt: "What is the main purpose of an algorithm?",
      optionA: "To provide a step-by-step solution to a problem",
      optionB: "To manage data storage",
      optionC: "To design hardware components",
      optionD: "To handle user interfaces",
      answer: "A",
    },
    {
      prompt: "What is the full form of SQL?",
      optionA: "Structured Query Language",
      optionB: "Structured Quality Language",
      optionC: "System Query Language",
      optionD: "Simple Query Language",
      answer: "A",
    },
  ];
  